### ISSUE TITLE
Missing including skin CSS file in demo guideline

### ISSUE THREAD

**Issue by SuTran** [flowplayer/flowplayer-hlsjs#64]
In demo page: `http://demos.flowplayer.org/api/hlsjs.html`
It should guide user to include `//releases.flowplayer.org/7.0.2/skin/skin.css` file to have the demo run correctly

**Comment by blacktrash** [comment]
@SuTran - the skin is not hlsjs specific, you have to load it for the core player anyway?
The point of the sample code snippet is that you load the plugin after the core player.

**Comment by SuTran** [comment]
Hi @blacktrash - Thanks for your answer.

So, what is the point of the below style snippet mentioned in the demo. Below code isn't make sense when using alone - without the skin.css

``` css
#hlsjsvod {
  background-image: url(//drive.cdn.flowplayer.org/202777/84049-snap.jpg);
}
#hlsjslive {
  background-color: #2f2f4f;
}
```
